# Generated by Django 2.1.3 on 2018-12-03 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeeManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.PositiveIntegerField(default=10000)),
                ('memo', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('off', 'off'), ('on', 'on')], default='on', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('members', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['select_month'],
            },
        ),
        migrations.CreateModel(
            name='MonthList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_month', models.CharField(choices=[('0', '월선택'), ('1', '1월'), ('2', '2월'), ('3', '3월'), ('4', '4월'), ('5', '5월'), ('6', '6월'), ('7', '7월'), ('8', '8월'), ('9', '9월'), ('10', '10월'), ('11', '11월'), ('12', '12월')], default='0', max_length=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='monthlist',
            name='make_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_app.YearList'),
        ),
        migrations.AddField(
            model_name='feemanager',
            name='select_month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='membership_app.MonthList'),
        ),
    ]
