# Generated by Django 2.1.3 on 2018-12-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_app', '0003_feemanager_using'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monthlist',
            options={'ordering': ['-created_at']},
        ),
    ]
