# Generated by Django 2.2 on 2020-04-05 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership_app', '0004_auto_20181207_1418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feemanager',
            name='members',
            field=models.CharField(choices=[('회원명', '회원명'), ('남영경', '남영경'), ('남영석', '남영석'), ('임용빈', '임용빈'), ('임영빈', '임영빈'), ('임규빈', '임규빈'), ('제갈익', '제갈익'), ('제갈륜', '제갈륜'), ('박수려', '박수려'), ('박민찬', '박민찬'), ('김은지', '김은지'), ('김병수', '김병수'), ('제갈민', '제갈민'), ('제갈웅', '제갈웅')], default='회원명', max_length=10),
        ),
    ]
