# Generated by Django 3.2.6 on 2022-01-11 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('membership_app', '0006_monthlist_month_fee'),
    ]

    operations = [
        migrations.RunSQL(
            'ALTER SEQUENCE membership_app_feemanager_id_seq RESTART WITH 300;'
        )
    ]
